# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: boot.fm
email: timaki.st@gmail.com
description: A podcast by timakin and k0kubun, talking about technology, business news, and anime etc...
baseurl: "" # the subpath of your site, e.g. /blog
lang: "ja"
url: "https://bootfm.github.io" # the base hostname & protocol for your site
twitter_username: bootfm
github_username:  bootfm
disqus_username:
actors:
  timakin:
    image_url: /images/profile/timakin.jpg
    name: timakin
    url: https://twitter.com/__timakin__
  k0kubun:
    image_url: /images/profile/k0kubun.png
    name: k0kubun
    url: https://twitter.com/k0kubun

# Build settings
markdown: kramdown
relative_permalinks: false
permalink: /:categories/:title/

# Posts settings
future: true
safe: false
lsi: false
excerpt_separator: "\n\n"


compress_html:
  comments: ["<!-- ", " -->"]
  clippings: all
  endings: all


sass:
  sass_dir: assets/_sass


images: '/images'
